# Generated by Django 5.0.6 on 2024-07-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
    ]
