# Generated by Django 5.0.6 on 2024-07-04 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Perfumes', '0002_alter_producto_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table=None,
        ),
    ]
